# Agent Configuration Template
# This file defines the core agent settings and capabilities

agent:
  name: "${AGENT_NAME:AuthenticatedAgent}"
  version: "${AGENT_VERSION:1.0.0}"
  description: "${AGENT_DESCRIPTION:An AI agent template with OAuth authentication capabilities}"

  # Model configuration
  model:
    provider: "${MODEL_PROVIDER:gemini}"
    name: "${MODEL_NAME:gemini-2.0-flash}"
    use_vertex_ai: "${USE_VERTEX_AI:true}"

  # Agent capabilities
  capabilities:
    streaming: true
    push_notifications: "${ENABLE_PUSH_NOTIFICATIONS:false}"
    authenticated_extended_card: true

  # Input/Output modes
  input_modes:
    - "text/plain"
    - "application/json"
  output_modes:
    - "text/plain"
    - "application/json"
    - "text/markdown"

# A2A Server Configuration
a2a:
  host: "${A2A_HOST:0.0.0.0}"
  port: "${A2A_PORT:8000}"
  preferred_transport: "${A2A_TRANSPORT:jsonrpc}"

  # Agent card configuration
  agent_card:
    url: "${AGENT_URL:http://localhost:8000}"
    documentation_url: "${AGENT_DOCS_URL:}"
    icon_url: "${AGENT_ICON_URL:}"
    provider:
      name: "${PROVIDER_NAME:Your Organization}"
      url: "${PROVIDER_URL:}"

# Skills that this agent can perform (customize for your specific agent)
skills:
  - id: "authenticated_operations"
    name: "Authenticated Operations"
    description: "Performs operations requiring OAuth authentication"
    tags: ["authentication", "oauth", "secure"]
    examples:
      - "Help me access my authenticated data"
      - "What can you do with my authentication?"
      - "Show me my information"

  - id: "example_skill"
    name: "Example Skill"
    description: "Example skill demonstrating OAuth integration (customize this)"
    tags: ["example", "template", "oauth"]
    examples:
      - "Run an example authenticated action"
      - "Test my authentication"
      - "Show me a demo"

# Environment-specific overrides
environments:
  development:
    agent:
      name: "${AGENT_NAME:AuthenticatedAgent}-dev"
    a2a:
      host: "localhost"
    logging:
      level: "DEBUG"

  staging:
    agent:
      name: "${AGENT_NAME:AuthenticatedAgent}-staging"
    logging:
      level: "INFO"

  production:
    logging:
      level: "WARNING"