# Agent Configuration Template
# This file defines the core agent settings and capabilities

agent:
  name: "${AGENT_NAME:ProfileAgent}"
  version: "${AGENT_VERSION:1.0.0}"
  description: "${AGENT_DESCRIPTION:An AI agent that provides user profile information through OAuth authentication}"

  # Model configuration
  model:
    provider: "${MODEL_PROVIDER:gemini}"
    name: "${MODEL_NAME:gemini-2.0-flash}"
    use_vertex_ai: "${USE_VERTEX_AI:true}"

  # Agent capabilities
  capabilities:
    streaming: true
    push_notifications: "${ENABLE_PUSH_NOTIFICATIONS:false}"
    authenticated_extended_card: true

  # Input/Output modes
  input_modes:
    - "text/plain"
    - "application/json"
  output_modes:
    - "text/plain"
    - "application/json"
    - "text/markdown"

# A2A Server Configuration
a2a:
  host: "${A2A_HOST:0.0.0.0}"
  port: "${A2A_PORT:8000}"
  preferred_transport: "${A2A_TRANSPORT:jsonrpc}"

  # Agent card configuration
  agent_card:
    url: "${AGENT_URL:http://localhost:8000}"
    documentation_url: "${AGENT_DOCS_URL:}"
    icon_url: "${AGENT_ICON_URL:}"
    provider:
      name: "${PROVIDER_NAME:Your Organization}"
      url: "${PROVIDER_URL:}"

# Skills that this agent can perform
skills:
  - id: "user_profile_access"
    name: "User Profile Access"
    description: "Retrieves user profile information using OAuth authentication"
    tags: ["profile", "user", "authentication", "oauth"]
    examples:
      - "What is my profile?"
      - "Show me my profile information"
      - "Get my user details"
      - "What's my email address?"

  - id: "profile_summary"
    name: "Profile Summary"
    description: "Provides a formatted summary of user profile data"
    tags: ["profile", "summary", "user-info"]
    examples:
      - "Give me a summary of my account"
      - "Tell me about myself"
      - "What information do you have about me?"

# Environment-specific overrides
environments:
  development:
    agent:
      name: "${AGENT_NAME:ProfileAgent}-dev"
    a2a:
      host: "localhost"
    logging:
      level: "DEBUG"

  staging:
    agent:
      name: "${AGENT_NAME:ProfileAgent}-staging"
    logging:
      level: "INFO"

  production:
    logging:
      level: "WARNING"