# Agent Configuration Template
# This file defines the core agent settings and capabilities

agent:
  name: "${AGENT_NAME:MyAgent}"
  version: "${AGENT_VERSION:1.0.0}"
  description: "${AGENT_DESCRIPTION:A configurable ADK agent with OAuth authentication}"

  # Model configuration
  model:
    provider: "${MODEL_PROVIDER:gemini}"
    name: "${MODEL_NAME:gemini-2.0-flash}"
    use_vertex_ai: "${USE_VERTEX_AI:true}"

  # Agent capabilities
  capabilities:
    streaming: true
    push_notifications: "${ENABLE_PUSH_NOTIFICATIONS:false}"
    authenticated_extended_card: true

  # Input/Output modes
  input_modes:
    - "text/plain"
    - "application/json"
  output_modes:
    - "text/plain"
    - "application/json"
    - "text/markdown"

# A2A Server Configuration
a2a:
  host: "${A2A_HOST:0.0.0.0}"
  port: "${A2A_PORT:8000}"
  preferred_transport: "${A2A_TRANSPORT:jsonrpc}"

  # Agent card configuration
  agent_card:
    url: "${AGENT_URL:http://localhost:8000}"
    documentation_url: "${AGENT_DOCS_URL:}"
    icon_url: "${AGENT_ICON_URL:}"
    provider:
      name: "${PROVIDER_NAME:Your Organization}"
      url: "${PROVIDER_URL:}"

# Skills that this agent can perform
skills:
  - id: "authenticated_api_call"
    name: "Authenticated API Call"
    description: "Makes authenticated API calls using user credentials"
    tags: ["api", "authentication", "secure"]
    examples:
      - "Can you fetch my profile data?"
      - "Get my account information"

  - id: "data_processing"
    name: "Data Processing"
    description: "Processes data with user authentication"
    tags: ["data", "processing", "secure"]
    examples:
      - "Process my uploaded file"
      - "Analyze my data"

# Environment-specific overrides
environments:
  development:
    agent:
      name: "${AGENT_NAME:MyAgent}-dev"
    a2a:
      host: "localhost"
    logging:
      level: "DEBUG"

  staging:
    agent:
      name: "${AGENT_NAME:MyAgent}-staging"
    logging:
      level: "INFO"

  production:
    logging:
      level: "WARNING"