# Remote Agents Configuration
#
# This file defines remote agents that can be used as sub-agents by the main agent.
# If this file doesn't exist or is empty, the agent runs in standalone mode.
#
# Each remote agent must:
# 1. Be running and accessible at the specified agent_card_url
# 2. Expose a valid agent card at /.well-known/agent-card.json
# 3. Support A2A protocol for receiving delegated tasks
#
# Authentication context (bearer tokens, OAuth) is automatically forwarded
# to remote agents when tasks are delegated.

remote_agents:
  # Auth Validation Agent - Template-based agent for testing authentication forwarding
  - name: "auth_validation_agent"
    description: "Validates authentication context forwarding via A2A protocol using the full template infrastructure"
    agent_card_url: "http://localhost:8002"
    enabled: true

  # Disabled agents for testing - uncomment to enable
  # - name: "data_analysis_agent"
  #   description: "Handles complex data analysis, statistical computations, data visualization, and reporting tasks"
  #   agent_card_url: "http://localhost:8003"
  #   enabled: false

  # - name: "notification_agent"
  #   description: "Sends notifications, alerts, emails, SMS, and handles all communication tasks"
  #   agent_card_url: "http://localhost:8004"
  #   enabled: false

# Configuration Notes:
# - Set enabled: false to disable a specific agent without removing its configuration
# - agent_card_url should point to the base A2A endpoint (/.well-known/agent-card.json will be appended automatically)
# - Each agent should run on a different port to avoid conflicts
# - Authentication context is automatically forwarded when delegating tasks

# To disable all remote agents:
# Comment out the entire remote_agents section or set it to an empty list:
# remote_agents: []